name: Deploy catalog-server

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Display Vercel CLI Version
        run: vercel --version

      - name: Display Node.js Version
        run: node --version

      - name: Install Dependencies
        run: pnpm install

      - name: Display pnpm Version
        run: pnpm --version

      - name: Run Build Command
        run: pnpm node scripts/build.js && mkdir -p public && touch public/index.html

      - name: List Generated Files
        run: ls -R

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --token $VERCEL_TOKEN --prod
